---
layout: topic
title: "Homework 4"
output: html_document
---

```{r include = FALSE}

# This code block sets up the r session when the page is rendered to html
# include = FALSE means that it will not be included in the html document

# Write every code block to the html document 
knitr::opts_chunk$set(echo = TRUE)

# Write the results of every code block to the html document 
knitr::opts_chunk$set(eval = TRUE)

# Set the web address where R will look for files from this repository
# Do not change this address
repo_url <- "https://raw.githubusercontent.com/LivingLandscapes/Course_EcologicalModeling/master/"

# Suppress warnings and messages
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 

```

## Overview




```{r, include = TRUE, eval = TRUE, message = FALSE}

# List of packages necessary to run this script:
require(librarian, quietly = TRUE)
shelf(tidyverse, 
      mgcv, # For checking model convergence
      MuMIn, # for model selection
      gratia, # for ggplot functionality with mgcv
      sf,
      lib = tempdir(),
      quiet = TRUE)

# Set the web address where R will look for files from this repository
# Do not change this address
repo_url <- "https://raw.githubusercontent.com/LivingLandscapes/Course_EcologicalModeling/master/"

# Load data
weather <- 
  read_csv(paste0(repo_url, "data/FireWeather.csv"))

# Brief looks at the data:
head(weather)

# Make a map of the weather stations:
weather_sf <- st_as_sf(weather,
                       crs = st_crs(4326),
                       coords = c("Long", "Lat"))
states_sf <- st_read(paste0(repo_url, 
                            "data/US_States/cb_2018_us_state_5m"))
ggplot() +
  geom_sf(data = states_sf, fill = "white") +
  geom_sf(mapping = aes(color = as.numeric(as.factor(Station_ID))), 
          data = weather_sf,
          shape = 2)

```
